version: "3.8"

services:
  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - postgres_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  postgres_adminer:
    image: adminer
    restart: always
    ports:
      - 8091:8080
    networks:
      - postgres_db

networks:
  postgres_db:
    external: false
    name: postgres_db

volumes:
  postgres-data:
    name: postgres-data
